#!/bin/bash

HASH="%C(always,yellow)%h%C(always,reset)"
RELATIVE_TIME="%C(always,green)(%ar)%C(always,reset)"
AUTHOR="%C(always,blue)<%an>%C(always,reset)"
SUBJECT="%s"
REFS="%C(always,red)%d%C(always,reset)"
FORMAT="$HASH{$RELATIVE_TIME{$AUTHOR{$REFS $SUBJECT"
function pretty_git_log() {

  git -c color.ui=always log --pretty="tformat:$FORMAT" | 
	column -t -s '|'

}
